name: build-macos-installer
on:
  push:
    tags:
      - "test-win-build-*"
jobs:
  setup-win-mingw-build-environment:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-potrace
            mingw-w64-x86_64-opencv
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-qt5-tools
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-gcc
            make
            libxml2
        
      - name: 
        shell: msys2 {0}
        run: |
          echo $PATH
          pwd
          mkdir build
          cd build
          export MINGW64_PATH=/mingw64
          qmake.exe -o Makefile ../swiftray.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
          #mingw32-make -j4
          make -j4
          ls
          
