name: build-macos-installer
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  setup-macos-build-environment:
    runs-on: macos-10.15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Select XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.3'
      #- uses: actions/setup-python@v3
      #  with:
      #    python-version: '3.9'
      #    cache: 'pip'
      - run: mkdir $RUNNER_WORKSPACE/dev/
      
      - name: Install dependencies for project
        run: |
          brew install icu4c
          brew install libxml2
      # Install Qt 5.15.2
      # NOTE: jurplel/install-qt-action@v2.14.0 hasn't supported Qt6.2.4
      - name: Install Qt 5.15.2
        run: |
          brew install p7zip
          python3 -m pip install setuptools wheel
          python3 -m pip install py7zr==0.16.1
          python3 -m pip install aqtinstall==2.1.0
          python3 -m aqt install-qt  mac desktop 5.15.2 -m debug_info -O $RUNNER_WORKSPACE/Qt
      # Build and Install Potrace library
      #- name: Restore Potrace cache
      #  uses: actions/cache@v3
      #  id: cache-potrace
      #  with:
      #    path: |
      #      /usr/local/lib/libpotrace.0.dylib
      #      /usr/local/lib/libpotrace.a
      #      /usr/local/lib/libpotrace.dylib
      #      /usr/local/lib/libpotrace.la
      #    key: potrace

      - name: Install Potrace
        #if: steps.cache-potrace.outputs.cache-hit != 'true'
        run: |
            cd $RUNNER_WORKSPACE/dev/
            curl http://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz -o potrace-1.16.tar.gz
            tar -xvf potrace-1.16.tar.gz
            cd potrace-1.16
            ./configure --with-libpotrace
            make install
      # Build and Install OpenCV library
      #- name: Restore OpenCV cache
      #  uses: actions/cache@v3
      #  id: cache-opencv
      #  with:
      #    path: |
      #      /usr/local/include/opencv4/
      #      /usr/local/lib/libopencv_**.dylib
      #      /usr/local/bin/opencv_**
      #      /usr/local/share/licenses/opencv4
      #      /usr/local/share/opencv4
      #      /usr/local/lib/cmake/opencv4
      #      /usr/local/bin/setup_vars_opencv4.sh
      #    key: opencv
      - name: Install OpenCV
        #if: steps.cache-opencv.outputs.cache-hit != 'true'
        run: |
          brew install opencv
      
      - name: QMake project
        run: |
          mkdir build
          cd build
          $RUNNER_WORKSPACE/Qt/5.15.2/clang_64/bin/qmake ${{ github.workspace }}/swiftray.pro -spec macx-clang CONFIG+=qtquickcompiler
      - name: Compile (Build) project
        run: |
          cd build
          make qmake_all
          make -j10
      - run: |
          brew install tree
      - name: Deploy (Copy necessary shared libraries)
        run: |
          cd build
          $RUNNER_WORKSPACE/Qt/5.15.2/clang_64/bin/macdeployqt Swiftray.app -qmldir=${{ github.workspace }}/src/windows/qml -verbose=2
          tree .

      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: build
      #    path: build/ # or path/to/artifact

      - name: Select XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4.0'

      #- uses: actions/download-artifact@v3
      #  with:
      #    name: build
      #- run: ls

      - name: Codesign executable
        env: 
          MACOS_CERTIFICATE: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          MACOS_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          #SIGN_IDENTITY_ID: 
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $MACOS_KEYCHAIN_PASSWORD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $MACOS_KEYCHAIN_PASSWORD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_KEYCHAIN_PASSWORD build.keychain
          cd build
          /usr/bin/codesign --force --deep --verify --verbose --timestamp --options runtime --sign "Developer ID Application: FLUX TECHNOLOGY CORP. (4Y92JWKV94)" "Swiftray.app"

      - name: Notarize Release Build
        env: 
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
        uses: erwin1/xcode-notarize@main
        with:
          product-path: "build/Swiftray.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
          asc-provider: ${{ secrets.ASC_PROVIDER }}
          verbose: true

      - name: "Staple Release Build"
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "build/Swiftray.app"

      - name: Create dmg
        run: |
          brew install create-dmg
          cd build
          create-dmg --volname "Swiftray Installer" \
            --volicon "Swiftray.app/Contents/Resources/icon.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 128 \
            --icon "Swiftray.app" 200 190 \
            --hide-extension "Swiftray.app" \
            --app-drop-link 600 190 \
            "Swiftray-Installer.dmg" \
            "Swiftray.app/"
                
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/Swiftray-Installer.dmg
